name: budget_scanner
description: "A local-first expense tracker."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # The Database Engine (Super fast NoSQL)
  objectbox: ^2.4.0
  objectbox_flutter_libs: ^2.4.0
  # Helper to find where to save files on Android
  path_provider: ^2.1.2
  path: ^1.9.0
  flutter_sms_inbox: ^1.0.1
  permission_handler: ^11.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # The Code Generator (Writes the C++ bridge for you)
  build_runner: ^2.4.8
  objectbox_generator: ^2.4.0
  # Linter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true